theme: "liquorice"
params:
  enableRSS: false
  gaCode: "UA-65857687-3"
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "https://www.iopanic.com/"
menu:
  main:
      - Name: "About"
        Identifier: "about-me"
        URL: "/about/"
      - Name: "Keybase"
        Identifier: "keybase"
        URL: "https://keybase.io/iopanic"
      - Name: "Github"
        Identifier: "github"
        URL: "https://github.com/marianzange"
title: "iopanic"
canonifyurls: true
