theme: "hugo-cactus-theme"
params:
  name: "Marian Zange"
  description: "Describe your website"
  bio: "I build software and study earth science."
  enableRSS: true
  copyright: |
             This blog is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">Creative Commons BY-NC 4.0 License</a>.
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "http://iopanic.github.io/"
title: "iopanic"
canonifyurls: true
