theme: "liquorice"
params:
  enableRSS: false
  gaCode: "UA-65857687-3"
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "http://www.iopanic.com/"
menu:
  main:
      - Name: "About"
        Identifier: "about-me"
        URL: "/page/about/"
      - Name: "Contact"
        Identifier: "contact"
        URL: "/page/contact/"
title: "iopanic"
canonifyurls: true
